#!/usr/bin/env python3
"""V6 Stage 2 trainer: copy head only, one skin.

Trains SlotNetV6 against the V6 copy-stage losses (L_copy_rgb + L_conf + L_uv +
L_uv_tv) using labels generated by scripts/16_make_v6_dataset.py.

Acceptance gates (per the V6 plan):

    visible MAE < 0.01
    copy_conf AUC > 0.98
    UV median error < 2 input pixels

    Eval is intended via scripts/17_eval_slotnet_v6.py against the same train CSV.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch
from torch.utils.data import DataLoader

REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

from atlas_ai.dataset_v6 import V6CopyDataset
from atlas_ai.export_spec import TRAINABLE_EXPORT_SPECS
from models.losses_v6 import V6CopyLossWeights, compute_v6_copy_stage_loss
from models.slotnet_v6 import SlotNetV6


def save_state_dict(path: Path, state_dict: dict) -> None:
    from safetensors.torch import save_file
    path.parent.mkdir(parents=True, exist_ok=True)
    save_file(state_dict, str(path))


def load_state_dict(path: Path) -> dict:
    from safetensors.torch import load_file
    return load_file(str(path))


def compute_step_loss(
    model: SlotNetV6,
    batch: dict,
    weights: V6CopyLossWeights,
    device: torch.device,
    *,
    uv_loss_mode: str = "normalized",
    uv_beta_px: float = 2.0,
    residual_scale: float = 0.25,
    use_residual: bool = False,
) -> dict[str, torch.Tensor]:
    """One training step: forward, compute per-file losses, sum across files."""
    view = batch["view"].to(device, non_blocking=True)
    output = model(view)
    files = output["files"]

    totals: dict[str, torch.Tensor] = {
        "copy_rgb": torch.zeros((), device=device),
        "conf": torch.zeros((), device=device),
        "uv": torch.zeros((), device=device),
        "uv_tv": torch.zeros((), device=device),
        "residual_l1": torch.zeros((), device=device),
        "total": torch.zeros((), device=device),
    }
    n_files = 0
    for spec in TRAINABLE_EXPORT_SPECS:
        labels = batch["files"][spec.file_name]
        target = labels["target"].to(device, non_blocking=True)
        visible = labels["visible"].to(device, non_blocking=True)
        uv_target = labels["uv"].to(device, non_blocking=True)
        head_out = files[spec.file_name]
        residual = head_out.get("residual") if use_residual else None
        loss_terms = compute_v6_copy_stage_loss(
            view=view,
            uv_pred=head_out["uv"],
            conf_logits=head_out["conf_logits"],
            target_rgb=target,
            visible_mask=visible,
            uv_target=uv_target,
            weights=weights,
            uv_loss_mode=uv_loss_mode,
            uv_beta_px=uv_beta_px,
            residual=residual,
            residual_scale=residual_scale,
        )
        totals["total"] = totals["total"] + loss_terms["total"]
        for key in ("copy_rgb", "conf", "uv", "uv_tv", "residual_l1"):
            totals[key] = totals[key] + loss_terms[key]
        n_files += 1
    if n_files:
        for key in totals:
            totals[key] = totals[key] / n_files
    return totals


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train", required=True, help="V6 train.csv")
    parser.add_argument("--skin-source", required=True, help="Directory of clean exported BMPs")
    parser.add_argument("--out", required=True)
    parser.add_argument("--steps", type=int, default=10000)
    parser.add_argument("--batch", type=int, default=2)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--base-channels", type=int, default=24)
    parser.add_argument("--style-dim", type=int, default=192)
    parser.add_argument("--head-channels", type=int, default=96)
    parser.add_argument("--attn-dim", type=int, default=128)
    parser.add_argument("--attention-heads", type=int, default=4)
    parser.add_argument("--cross-attention-layers", type=int, default=1)
    parser.add_argument("--file-embedding-dim", type=int, default=32)
    parser.add_argument("--query-grid-divisor", type=int, default=4)
    parser.add_argument("--weight-copy-rgb", type=float, default=1.0)
    parser.add_argument("--weight-conf", type=float, default=0.25)
    parser.add_argument("--weight-uv", type=float, default=0.10)
    parser.add_argument("--weight-uv-tv", type=float, default=0.01)
    parser.add_argument("--weight-residual-l1", type=float, default=0.0,
                        help="L1 penalty on residual. >0 enables copy_refined path "
                             "(copy_rgb + scale * tanh(residual)) in the loss.")
    parser.add_argument("--residual-scale", type=float, default=0.25,
                        help="Maximum residual magnitude per pixel (matches V6 plan).")
    parser.add_argument("--uv-loss", choices=["normalized", "pixel"], default="normalized",
                        help="UV smooth-L1 loss space. 'pixel' matches the eval metric "
                             "(use with --weight-uv >= 1.0 for UV-first training).")
    parser.add_argument("--uv-beta-px", type=float, default=2.0,
                        help="Pixel-space smooth-L1 transition. Default 2.0 = Stage 2 bar.")
    parser.add_argument("--resume-from", default=None,
                        help="Path to a .safetensors checkpoint whose weights seed the model. "
                             "Steps restart at 0; the new --out is independent of the source run.")
    parser.add_argument("--freeze-except-residual", action="store_true",
                        help="Freeze every parameter except per-file residual_proj. Used to "
                             "isolate the residual head's contribution from backbone drift.")
    parser.add_argument("--checkpoint-every", type=int, default=1000)
    parser.add_argument("--snapshot-every", type=int, default=1000)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument("--pin-memory", action="store_true")
    parser.add_argument("--persistent-workers", action="store_true")
    parser.add_argument("--prefetch-factor", type=int, default=2)
    parser.add_argument("--amp", action="store_true")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = parser.parse_args()

    device = torch.device(args.device)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    dataset = V6CopyDataset(args.train, args.skin_source)
    dl_kwargs = dict(
        batch_size=args.batch,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=args.pin_memory and device.type == "cuda",
        drop_last=False,
    )
    if args.num_workers > 0:
        dl_kwargs["persistent_workers"] = args.persistent_workers
        dl_kwargs["prefetch_factor"] = args.prefetch_factor
    loader = DataLoader(dataset, **dl_kwargs)

    model = SlotNetV6(
        base_channels=args.base_channels,
        style_dim=args.style_dim,
        head_channels=args.head_channels,
        attn_dim=args.attn_dim,
        attention_heads=args.attention_heads,
        cross_attention_layers=args.cross_attention_layers,
        file_embedding_dim=args.file_embedding_dim,
        query_grid_divisor=args.query_grid_divisor,
    ).to(device)

    if args.resume_from:
        resume_state = load_state_dict(Path(args.resume_from))
        version = int(resume_state.get("slotnet_version", torch.tensor([0])).reshape(-1)[0].item())
        if version != 60:
            raise SystemExit(f"--resume-from expects V6 (60) checkpoint, got {version}")
        # strict=False so a pre-residual checkpoint can be dropped into a
        # residual-equipped model: residual_proj keeps its zero init.
        missing, unexpected = model.load_state_dict(resume_state, strict=False)
        missing_set = set(missing)
        residual_missing = {k for k in missing_set if "residual_proj" in k}
        non_residual_missing = missing_set - residual_missing
        if non_residual_missing:
            raise SystemExit(
                f"--resume-from is missing required keys: {sorted(non_residual_missing)[:5]}..."
            )
        if unexpected:
            raise SystemExit(f"--resume-from has unexpected keys: {sorted(unexpected)[:5]}...")
        if residual_missing:
            print(f"resumed weights from {args.resume_from} "
                  f"(residual head freshly zero-initialized)")
        else:
            print(f"resumed weights from {args.resume_from}")

    if args.freeze_except_residual:
        for name, param in model.named_parameters():
            param.requires_grad_("residual_proj" in name)
        trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
        total = sum(p.numel() for p in model.parameters())
        print(f"freeze-except-residual: {trainable:,} / {total:,} params trainable")

    trainable_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = torch.optim.AdamW(
        trainable_params,
        lr=args.lr,
        weight_decay=args.weight_decay,
        betas=(0.9, 0.95),
    )
    scaler = torch.amp.GradScaler("cuda", enabled=args.amp and device.type == "cuda")
    weights = V6CopyLossWeights(
        copy_rgb=args.weight_copy_rgb,
        conf=args.weight_conf,
        uv=args.weight_uv,
        uv_tv=args.weight_uv_tv,
        residual_l1=args.weight_residual_l1,
    )
    use_residual = args.weight_residual_l1 > 0.0

    config = {
        "model_version": 60,
        "args": vars(args),
        "weights": {
            "copy_rgb": weights.copy_rgb,
            "conf": weights.conf,
            "uv": weights.uv,
            "uv_tv": weights.uv_tv,
        },
        "dataset_rows": len(dataset),
    }
    (out / "config.json").write_text(json.dumps(config, indent=2, sort_keys=True))

    metrics_path = out / "metrics.jsonl"
    best = float("inf")
    last_total = float("nan")
    step = 0
    model.train()
    with metrics_path.open("w", encoding="utf-8") as metrics_file:
        while step < args.steps:
            for batch in loader:
                if step >= args.steps:
                    break
                optimizer.zero_grad(set_to_none=True)
                with torch.amp.autocast(
                    "cuda",
                    enabled=args.amp and device.type == "cuda",
                ):
                    losses = compute_step_loss(
                        model, batch, weights, device,
                        uv_loss_mode=args.uv_loss,
                        uv_beta_px=args.uv_beta_px,
                        residual_scale=args.residual_scale,
                        use_residual=use_residual,
                    )
                if args.amp and device.type == "cuda":
                    scaler.scale(losses["total"]).backward()
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    losses["total"].backward()
                    optimizer.step()

                logged = {key: float(value.detach().cpu()) for key, value in losses.items()}
                logged["step"] = step
                last_total = logged["total"]
                metrics_file.write(json.dumps(logged) + "\n")
                if (step + 1) % args.checkpoint_every == 0 or step == 0:
                    save_state_dict(out / "last.safetensors", model.state_dict())
                if logged["total"] < best:
                    best = logged["total"]
                    save_state_dict(out / "best.safetensors", model.state_dict())
                if args.snapshot_every > 0 and (step + 1) % args.snapshot_every == 0:
                    save_state_dict(
                        out / f"snapshot_step{step + 1:06d}.safetensors",
                        model.state_dict(),
                    )
                step += 1
    save_state_dict(out / "last.safetensors", model.state_dict())
    print(
        f"trained SlotNetV6 for {step} step(s); "
        f"last total loss {last_total:.6f}; best total loss {best:.6f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
