input:
  width: 960
  height: 1728
atlas:
  width: 1024
  height: 1024
  profile: configs/atlas_train_v1.json
export:
  profile: configs/export_profile_classic.json
data:
  root: data_v34
  split_by: skin_id
slotnet:
  version: 34
  active_slots:
    - MAIN
    - TITLEBAR
    - CBUTTONS
    - SHUFREP
    - MONOSTER
    - PLAYPAUS
    - EQMAIN
    - PLEDIT
    - POSBAR
    - VOLUME
    - BALANCE
