"""SlotNetV6 (Stage 2 copy-head-only): source-preserving inverse renderer.

V6 changes V5's per-file decoder from "generate RGB" to "locate visible source
pixels in the input view". Each per-file head predicts:

    uv_grid          [B, 2, H, W]   in [-1, 1], align_corners=False conventions
    copy_conf_logits [B, 1, H, W]   raw logits (sigmoid in loss/composition)

At inference time the model uses:

    copy_rgb = grid_sample(input_view, uv_grid.permute(0, 2, 3, 1),
                           align_corners=False)
    alpha    = sigmoid(copy_conf_logits)
    final    = alpha * copy_rgb + (1 - alpha) * <fallback>

In Stage 2 we omit the fallback path and train the copy head against the
visible-pixel labels generated by the cranamp final-frame provenance buffer.
This module deliberately exposes only uv + conf so the Stage 2 loss cannot
accidentally leak gradients through residual/fallback paths that have not been
validated.

The output API mirrors V5 for ease of dispatch:

    model(view) -> {"files": {file_name: {"uv": ..., "conf_logits": ...}}}

Set return_attention=True to additionally get per-file attention summaries
shaped (B, h_enc, w_enc) for debug heatmaps.
"""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F
from torch import nn

from atlas_ai.export_spec import TRAINABLE_EXPORT_SPECS, ExportFileSpec

# Defaults per HANDOFF V6. residual_scale / fallback are not used in Stage 2.
DEFAULT_FREQUENCIES = (1, 2, 4, 8)
QUERY_GRID_DIVISOR = 4  # V6 plan: denser query grid than V5's 8


def _groups(channels: int, preferred: int) -> int:
    return preferred if channels % preferred == 0 else 1


def conv_block(in_ch: int, out_ch: int, preferred_groups: int, stride: int = 1) -> nn.Sequential:
    groups = _groups(out_ch, preferred_groups)
    return nn.Sequential(
        nn.Conv2d(in_ch, out_ch, 3, stride=stride, padding=1),
        nn.GroupNorm(groups, out_ch),
        nn.SiLU(inplace=True),
        nn.Conv2d(out_ch, out_ch, 3, padding=1),
        nn.GroupNorm(groups, out_ch),
        nn.SiLU(inplace=True),
    )


def _coord_channels(frequencies: tuple[int, ...]) -> int:
    return 2 + 4 * len(frequencies)


def _head_key(file_name: str) -> str:
    return file_name.lower().removesuffix(".bmp")


def _query_grid_size(spec: ExportFileSpec, divisor: int) -> tuple[int, int]:
    return (
        max(1, math.ceil(spec.h / divisor)),
        max(1, math.ceil(spec.w / divisor)),
    )


def _decoder_upsample_blocks(divisor: int) -> int:
    """Number of x2 upsample blocks the decoder needs to reach file resolution
    from a (h/divisor, w/divisor) query grid (rounded up to the nearest
    power-of-two scale factor)."""
    n = max(1, divisor)
    blocks = 0
    while (1 << blocks) < n:
        blocks += 1
    return blocks


def build_fourier_coords(height: int, width: int, frequencies: tuple[int, ...]) -> torch.Tensor:
    y01 = torch.linspace(0.0, 1.0, height)
    x01 = torch.linspace(0.0, 1.0, width)
    yy01, xx01 = torch.meshgrid(y01, x01, indexing="ij")
    channels = [xx01 * 2.0 - 1.0, yy01 * 2.0 - 1.0]
    for freq in frequencies:
        angle_x = 2.0 * math.pi * freq * xx01
        angle_y = 2.0 * math.pi * freq * yy01
        channels.extend((torch.sin(angle_x), torch.cos(angle_x), torch.sin(angle_y), torch.cos(angle_y)))
    return torch.stack(channels, dim=0)


class CopyHead(nn.Module):
    """Per-file: query grid + cross-attention into encoder tokens, decode to
    (uv_grid, copy_conf_logits) at exact exported file dimensions.
    """

    def __init__(
        self,
        spec: ExportFileSpec,
        file_index: int,
        attn_dim: int,
        attention_heads: int,
        cross_attention_layers: int,
        style_dim: int,
        head_channels: int,
        file_embedding_dim: int,
        query_grid_divisor: int,
        frequencies: tuple[int, ...] = DEFAULT_FREQUENCIES,
    ):
        super().__init__()
        self.spec = spec
        self.file_index = file_index
        self.attn_dim = attn_dim

        h0, w0 = _query_grid_size(spec, query_grid_divisor)
        self.h0 = h0
        self.w0 = w0

        coord_channels = _coord_channels(frequencies)
        token_in_channels = coord_channels + file_embedding_dim + style_dim
        self.query_proj = nn.Linear(token_in_channels, attn_dim)

        self.cross_layers = nn.ModuleList(
            [
                nn.MultiheadAttention(
                    embed_dim=attn_dim,
                    num_heads=attention_heads,
                    batch_first=True,
                )
                for _ in range(cross_attention_layers)
            ]
        )
        self.norms = nn.ModuleList([nn.LayerNorm(attn_dim) for _ in range(cross_attention_layers)])
        self.ffns = nn.ModuleList(
            [
                nn.Sequential(
                    nn.Linear(attn_dim, attn_dim * 2),
                    nn.SiLU(inplace=True),
                    nn.Linear(attn_dim * 2, attn_dim),
                )
                for _ in range(cross_attention_layers)
            ]
        )
        self.ffn_norms = nn.ModuleList([nn.LayerNorm(attn_dim) for _ in range(cross_attention_layers)])

        groups = 8 if head_channels % 8 == 0 else 1
        upsample_blocks = _decoder_upsample_blocks(query_grid_divisor)
        body_layers: list[nn.Module] = [
            nn.Conv2d(attn_dim, head_channels, 1),
            nn.GroupNorm(groups, head_channels),
            nn.SiLU(inplace=True),
        ]
        for _ in range(upsample_blocks):
            body_layers.extend(
                [
                    nn.Upsample(scale_factor=2, mode="nearest"),
                    nn.Conv2d(head_channels, head_channels, 3, padding=1),
                    nn.GroupNorm(groups, head_channels),
                    nn.SiLU(inplace=True),
                ]
            )
        # One more conv at native scale to fold neighbour info before split.
        body_layers.extend(
            [
                nn.Conv2d(head_channels, head_channels, 3, padding=1),
                nn.GroupNorm(groups, head_channels),
                nn.SiLU(inplace=True),
            ]
        )
        self.body = nn.Sequential(*body_layers)
        self.uv_proj = nn.Conv2d(head_channels, 2, 1)
        self.conf_proj = nn.Conv2d(head_channels, 1, 1)
        # Zero-initialized residual projection: at training start, copy_refined
        # equals copy_rgb exactly. Lets us drop a residual head onto a frozen
        # sampler-trained checkpoint without disturbing it.
        self.residual_proj = nn.Conv2d(head_channels, 3, 1)
        nn.init.zeros_(self.residual_proj.weight)
        nn.init.zeros_(self.residual_proj.bias)

        self.register_buffer(
            "grid_coords",
            build_fourier_coords(h0, w0, frequencies).reshape(coord_channels, -1).T.contiguous(),
        )

    def build_queries(self, style: torch.Tensor, file_emb: torch.Tensor) -> torch.Tensor:
        batch = style.shape[0]
        coords = self.grid_coords.to(dtype=style.dtype, device=style.device)
        coords = coords.unsqueeze(0).expand(batch, -1, -1)
        emb = file_emb.to(dtype=style.dtype).view(1, 1, -1).expand(batch, self.h0 * self.w0, -1)
        style_per_cell = style.unsqueeze(1).expand(-1, self.h0 * self.w0, -1)
        combined = torch.cat((coords, emb, style_per_cell), dim=-1)
        return self.query_proj(combined)

    def forward(
        self,
        style: torch.Tensor,
        encoder_tokens: torch.Tensor,
        file_emb: torch.Tensor,
        *,
        return_attention: bool = False,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor | None]:
        queries = self.build_queries(style, file_emb)
        attn_summary: torch.Tensor | None = None
        for layer_idx, (attn, norm, ffn, ffn_norm) in enumerate(
            zip(self.cross_layers, self.norms, self.ffns, self.ffn_norms)
        ):
            normed = norm(queries)
            want_weights = return_attention and layer_idx == len(self.cross_layers) - 1
            attended, weights = attn(
                normed,
                encoder_tokens,
                encoder_tokens,
                need_weights=want_weights,
                average_attn_weights=True,
            )
            queries = queries + attended
            queries = queries + ffn(ffn_norm(queries))
            if want_weights and weights is not None:
                attn_summary = weights.mean(dim=1)
        batch = queries.shape[0]
        spatial = queries.transpose(1, 2).reshape(batch, self.attn_dim, self.h0, self.w0)
        feat = self.body(spatial)
        if feat.shape[-2:] != (self.spec.h, self.spec.w):
            feat = F.interpolate(feat, size=(self.spec.h, self.spec.w), mode="nearest")
        uv = torch.tanh(self.uv_proj(feat))
        conf_logits = self.conf_proj(feat)
        residual = self.residual_proj(feat)
        return uv, conf_logits, residual, attn_summary


class SlotNetV6(nn.Module):
    """Stage 2 copy-head-only V6 model.

    Outputs per file: uv_grid [B, 2, H, W] in [-1, 1] (align_corners=False
    grid_sample coords) and copy_conf_logits [B, 1, H, W]. Apply the V6 copy
    composition in the loss / inference path; this module does not run
    grid_sample itself so the same checkpoint can be evaluated against a
    different input resolution if needed."""

    def __init__(
        self,
        base_channels: int = 24,
        style_dim: int = 192,
        head_channels: int | None = None,
        attn_dim: int = 128,
        attention_heads: int = 4,
        cross_attention_layers: int = 1,
        file_embedding_dim: int = 32,
        query_grid_divisor: int = QUERY_GRID_DIVISOR,
        frequencies: tuple[int, ...] = DEFAULT_FREQUENCIES,
    ):
        super().__init__()
        if attn_dim % attention_heads != 0:
            raise ValueError(
                f"attn_dim={attn_dim} must be divisible by attention_heads={attention_heads}"
            )
        if attn_dim % 4 != 0:
            raise ValueError(f"attn_dim={attn_dim} must be divisible by 4 for 2D PE")
        head_channels = head_channels or base_channels * 4

        c1 = base_channels
        c2 = base_channels * 2
        c3 = base_channels * 4
        c4 = base_channels * 6
        c5 = base_channels * 8

        self.enc1 = conv_block(3, c1, 8, stride=1)
        self.enc2 = conv_block(c1, c2, 8, stride=2)
        self.enc3 = conv_block(c2, c3, 16, stride=2)
        self.enc4 = conv_block(c3, c4, 16, stride=2)
        self.enc5 = conv_block(c4, c5, 32, stride=2)

        self.style_proj = nn.Sequential(
            nn.Linear(c5, style_dim),
            nn.SiLU(inplace=True),
            nn.Linear(style_dim, style_dim),
        )

        self.feature_proj = nn.Conv2d(c5, attn_dim, kernel_size=1)
        self.attn_dim = attn_dim
        self._pe_cache: dict[tuple[int, int, torch.device, torch.dtype], torch.Tensor] = {}

        self.file_embedding = nn.Embedding(len(TRAINABLE_EXPORT_SPECS), file_embedding_dim)

        self.heads = nn.ModuleDict(
            {
                _head_key(spec.file_name): CopyHead(
                    spec=spec,
                    file_index=idx,
                    attn_dim=attn_dim,
                    attention_heads=attention_heads,
                    cross_attention_layers=cross_attention_layers,
                    style_dim=style_dim,
                    head_channels=head_channels,
                    file_embedding_dim=file_embedding_dim,
                    query_grid_divisor=query_grid_divisor,
                    frequencies=frequencies,
                )
                for idx, spec in enumerate(TRAINABLE_EXPORT_SPECS)
            }
        )

        self.register_buffer("slotnet_version", torch.tensor([60], dtype=torch.int32))
        self.register_buffer("attn_dim_buffer", torch.tensor([attn_dim], dtype=torch.int32))
        self.register_buffer("attention_heads_buffer", torch.tensor([attention_heads], dtype=torch.int32))
        self.register_buffer(
            "cross_attention_layers_buffer",
            torch.tensor([cross_attention_layers], dtype=torch.int32),
        )
        self.register_buffer(
            "query_grid_divisor_buffer",
            torch.tensor([query_grid_divisor], dtype=torch.int32),
        )
        self.register_buffer(
            "frequencies_buffer",
            torch.tensor(list(frequencies), dtype=torch.int32),
        )

    def _ensure_pos_table(self, h: int, w: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
        key = (h, w, device, dtype)
        cached = self._pe_cache.get(key)
        if cached is not None:
            return cached
        pe = _build_sinusoidal_2d_pe(h, w, self.attn_dim).to(device=device, dtype=dtype)
        self._pe_cache[key] = pe
        return pe

    def encode_features(self, view: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        f1 = self.enc1(view)
        f2 = self.enc2(f1)
        f3 = self.enc3(f2)
        f4 = self.enc4(f3)
        f5 = self.enc5(f4)
        return f5, self.style_proj(f5.mean(dim=(2, 3)))

    def feature_tokens(self, f5: torch.Tensor) -> torch.Tensor:
        projected = self.feature_proj(f5)
        _, _, h_enc, w_enc = projected.shape
        pos = self._ensure_pos_table(h_enc, w_enc, projected.device, projected.dtype)
        tokens = projected.flatten(2).transpose(1, 2)
        return tokens + pos.unsqueeze(0)

    def forward(
        self,
        view: torch.Tensor,
        *,
        return_attention: bool = False,
    ) -> dict[str, dict]:
        f5, style = self.encode_features(view)
        tokens = self.feature_tokens(f5)
        all_file_emb = self.file_embedding(
            torch.arange(len(self.heads), device=view.device)
        )
        outputs: dict[str, dict[str, torch.Tensor]] = {}
        attention: dict[str, torch.Tensor] = {}
        h_enc, w_enc = f5.shape[-2:]
        for head in self.heads.values():
            uv, conf_logits, residual, attn_summary = head(
                style,
                tokens,
                all_file_emb[head.file_index],
                return_attention=return_attention,
            )
            outputs[head.spec.file_name] = {
                "uv": uv,
                "conf_logits": conf_logits,
                "residual": residual,
            }
            if return_attention and attn_summary is not None:
                attention[head.spec.file_name] = attn_summary.reshape(-1, h_enc, w_enc)
        if return_attention:
            return {"files": outputs, "attention": attention}
        return {"files": outputs}


def _build_sinusoidal_2d_pe(h: int, w: int, dim: int) -> torch.Tensor:
    if dim % 4 != 0:
        raise ValueError(f"positional encoding dim must be divisible by 4, got {dim}")
    half = dim // 2
    pe = torch.zeros(h, w, dim)
    div_term = torch.exp(torch.arange(0, half, 2, dtype=torch.float32) * -(math.log(10000.0) / half))
    y_pos = torch.arange(h, dtype=torch.float32).unsqueeze(1)
    x_pos = torch.arange(w, dtype=torch.float32).unsqueeze(1)
    pe_y = torch.zeros(h, half)
    pe_y[:, 0::2] = torch.sin(y_pos * div_term)
    pe_y[:, 1::2] = torch.cos(y_pos * div_term)
    pe_x = torch.zeros(w, half)
    pe_x[:, 0::2] = torch.sin(x_pos * div_term)
    pe_x[:, 1::2] = torch.cos(x_pos * div_term)
    pe[:, :, :half] = pe_y.unsqueeze(1).expand(h, w, half)
    pe[:, :, half:] = pe_x.unsqueeze(0).expand(h, w, half)
    return pe.reshape(h * w, dim)


__all__ = ["SlotNetV6", "CopyHead", "build_fourier_coords"]
